=== Piecelet/neodb-public-api/data/servers/schema.json
{
    "name": "NeoDB Public Instance Info Schema",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "domain": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "languages": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "display_languages": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "region": {
        "type": "string"
      },
      "display_region": {
        "type": "string"
      },
      "categories": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "proxied_thumbnail": {
        "type": "string"
      },
      "blurhash": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "logo": {
        "type": "string"
      },
      "total_users": {
        "type": "integer"
      },
      "last_week_users": {
        "type": "integer"
      },
      "approval_required": {
        "type": "boolean"
      },
      "language": {
        "type": "string"
      },
      "display_language": {
        "type": "string"
      },
      "category": {
        "type": "string"
      }
    },
    "required": [
      "domain",
      "version",
      "description",
      "languages",
      "display_languages",
      "region",
      "categories",
      "proxied_thumbnail",
      "blurhash",
      "total_users",
      "last_week_users",
      "approval_required",
      "language",
      "category",
      "title"
    ]
  }

=== Piecelet/neodb-public-api/data/servers/servers-community.json
[
  {
    "domain": "minreol.dk",
    "version": "4.0.4 (compatible; NeoDB dev-unknown)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "europe",
    "display_region": "Europe",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://minreol.dk/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://minreol.dk/icon.png",
    "total_users": 138,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Minreol",
    "logo": "https://minreol.dk/logo.png"
  },
  {
    "domain": "neodb.kevga.de",
    "version": "4.0.4 (compatible; NeoDB 0.17.6-732be62-20260809214849)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "europe",
    "display_region": "Europe",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://neodb.kevga.de/static/img/fjords-banner-600.fa337a5055b6.jpg",
    "blurhash": "",
    "icon": "https://neodb.kevga.de/icon.png",
    "total_users": 64,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Kevga NeoDB",
    "logo": "https://neodb.kevga.de/logo.png"
  },
  {
    "domain": "fantastika.social",
    "version": "4.0.4 (compatible; NeoDB 0.19.6.3-467b5ce-20261004222308)",
    "description": "Comunidad hispanohablante de NeoDB para registrar, valorar y compartir libros, películas, música, juegos y podcasts.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://media.fantastika.social/config/2025/2/28/Z1Usn6g0S5l8jtgucRqrmQ9Qw8U.png",
    "blurhash": "",
    "icon": "https://fantastika.social/s/img/icon.png",
    "total_users": 46,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Fantastika",
    "logo": "https://fantastika.social/logo.png"
  },
  {
    "domain": "garage.o00o.lol",
    "version": "neodb/0.12.7.1-cccec03-97a82d1-20251229183537",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://garage.o00o.lol/media/config/2026/1/19/Pcp59J9AraXpWEeykVPJ2ADzVk8.jpg",
    "blurhash": "",
    "icon": "https://garage.o00o.lol/icon.png",
    "total_users": 12,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "O00o Garage",
    "logo": "https://git.o00o.lol/admin/image-garage/raw/branch/main/logo.png"
  },
  {
    "domain": "crititeca.illustietor.com",
    "version": "",
    "title": "Illustietor Crititeca",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "db.casually.cat",
    "version": "",
    "title": "Casually DB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "film.upstairs.cn",
    "version": "",
    "title": "Upstairs Film",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "icon": "https://film.upstairs.cn/favicon.ico",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": "",
    "logo": "https://film.upstairs.cn/logo.png"
  },
  {
    "domain": "lib.itinerariummentis.org",
    "version": "",
    "title": "Itinerariummentis Lib",
    "description": "Itinerarium in Librarium Mentis",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "icon": "https://lib.itinerariummentis.org/icon.png",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": "",
    "logo": "https://lib.itinerariummentis.org/logo.png"
  },
  {
    "domain": "log.melonbread.xyz",
    "version": "",
    "title": "Melonbread Log",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.mastodon.work",
    "version": "",
    "title": "Mastodon NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.neo-cities.homes",
    "version": "",
    "title": "Neo-cities NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.nickfi.de",
    "version": "",
    "title": "Nickfi NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "neodb.versi-tech.com",
    "version": "",
    "title": "Versi-tech NeoDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "polg.cn",
    "version": "",
    "title": "Polg",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "reviewdb.app",
    "version": "",
    "title": "ReviewDB",
    "description": "",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": ""
  },
  {
    "domain": "watch.socialyeti.club",
    "version": "",
    "title": "Socialyeti Watch",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [],
    "display_languages": [],
    "region": "",
    "categories": [],
    "proxied_thumbnail": "https://neodb.internal/placeholder",
    "blurhash": "",
    "icon": "https://watch.socialyeti.club/yeti-watch-icon.png",
    "total_users": 0,
    "last_week_users": 0,
    "approval_required": false,
    "language": "",
    "category": "",
    "logo": "https://watch.socialyeti.club/yeti-watch.png"
  }
]

=== Piecelet/neodb-public-api/data/servers/servers-official.json
[
  {
    "domain": "neodb.social",
    "version": "4.0.4 (compatible; NeoDB 0.19.7-811753c-20261006202638)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://neodb.social/m/config/2026/9/4/kOP4N3AMFC4hJn_UCH5ObHKsiTk.png",
    "blurhash": "",
    "icon": "https://neodb.social/s/img/icon.png",
    "total_users": 36846,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "NeoDB",
    "logo": "https://neodb.social/s/img/logo.svg"
  },
  {
    "domain": "eggplant.place",
    "version": "4.0.4 (compatible; NeoDB main-b5cb292-20261007234838)",
    "description": "Reviews about book, film, music, podcast and game.",
    "languages": [
      "en"
    ],
    "display_languages": [
      "English"
    ],
    "region": "",
    "categories": [
      "general"
    ],
    "proxied_thumbnail": "https://eggplant.place/m/config/2024/1/15/zSi9h6bAWx05WG0QFjRglP47HCs.webp",
    "blurhash": "",
    "icon": "https://eggplant.place/logo2.png",
    "total_users": 924,
    "last_week_users": 0,
    "approval_required": false,
    "language": "en",
    "display_language": "English",
    "category": "general",
    "title": "Eggplant",
    "logo": "https://eggplant.place/logo2.png"
  }
]
